# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestesDeCadastro():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testeDeCadastro(self):
    self.driver.get("http://localhost:8000/cadastro")
    self.driver.set_window_size(1849, 1080)
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_surname").click()
    self.driver.find_element(By.ID, "id_surname").send_keys("teste")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jonatasteste")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("teste1@gmail.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_conf_password").click()
    self.driver.find_element(By.ID, "id_conf_password").send_keys("jonatas")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

  def test_testeCadastroComSenhasInvalidas(self):
    self.driver.get("http://localhost:8000/cadastro")
    self.driver.set_window_size(1849, 1080)
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_surname").click()
    self.driver.find_element(By.ID, "id_surname").send_keys("teste")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jonatasteste")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("teste2@gmail.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_conf_password").click()
    self.driver.find_element(By.ID, "id_conf_password").send_keys("jonatas4")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()


  def test_testeCadastroVazio(self):
    self.driver.get("http://localhost:8000/cadastro")
    self.driver.set_window_size(1849, 1080)
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_surname").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_conf_password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

  
  def test_testeCadastroSemSenhaDeConfirmacao(self):
    self.driver.get("http://localhost:8000/cadastro")
    self.driver.set_window_size(1849, 1080)
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_surname").click()
    self.driver.find_element(By.ID, "id_surname").send_keys("teste")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jonatasteste")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("teste2@gmail.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_conf_password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

  
  def test_testeCadastroComEmailIncompleto(self):
    self.driver.get("http://localhost:8000/cadastro")
    self.driver.set_window_size(1849, 1080)
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_surname").click()
    self.driver.find_element(By.ID, "id_surname").send_keys("teste")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jonatasteste")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("teste2@")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_conf_password").click()
    self.driver.find_element(By.ID, "id_conf_password").send_keys("jonatas")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

  def test_testeCadastroComUsuarioComTipoDiferenteDeTexto(self):
    self.driver.get("http://localhost:8000/cadastro")
    self.driver.set_window_size(1849, 1080)
    self.driver.find_element(By.ID, "id_name").click()
    assert(self.vars["id=id_name"] == 1) #objetivo: verificar se o tipo da variavel nome é string
    self.driver.find_element(By.ID, "id_surname").click()
    self.driver.find_element(By.ID, "id_surname").send_keys("222")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jonatasteste")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("teste2@gmail.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_conf_password").click()
    self.driver.find_element(By.ID, "id_conf_password").send_keys("jonatas")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

  def test_testeCadastroComMaisCaracteresQueOPermitido(self):
    self.driver.get("http://localhost:8000/cadastro")
    self.driver.set_window_size(1849, 1080)
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_nome").send_keys("testeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")
    self.driver.find_element(By.ID, "id_surname").click()
    self.driver.find_element(By.ID, "id_surname").send_keys("222")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jonatasteste")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("teste2@gmail.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_conf_password").click()
    self.driver.find_element(By.ID, "id_conf_password").send_keys("jonatas")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

  def test_EmailSemOArroba(self):
    self.driver.get("http://localhost:8000/cadastro")
    self.driver.set_window_size(1849, 1080)
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_surname").click()
    self.driver.find_element(By.ID, "id_surname").send_keys("teste")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jonatasteste")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("teste2.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("jonatas")
    self.driver.find_element(By.ID, "id_conf_password").click()
    self.driver.find_element(By.ID, "id_conf_password").send_keys("jonatas")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()